### ISSUE TITLE
[compat] 1.20.6: Entity Culling

### ISSUE THREAD

**Issue by MeeniMc** [samolego/FabricTailor#102]
## Issue

- [x] I'm not using TLauncher (it messes up the skins, also, piracy is not supported)

**Describe the bug**

Error messages are generated in the log about 'out of bound access', usually that will cause bugs but  I didn't see something egregious atm. 

```
[12:29:40] [CullThread/INFO] (Minecraft) [STDERR]: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2586.method_11017()" because the return value of "java.util.Map$Entry.getValue()" is null
[12:29:40] [CullThread/INFO] (Minecraft) [STDERR]: 	at dev.tr7zw.entityculling.CullTask.cullBlockEntities(CullTask.java:148)
[12:29:40] [CullThread/INFO] (Minecraft) [STDERR]: 	at dev.tr7zw.entityculling.CullTask.run(CullTask.java:69)
[12:29:40] [CullThread/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[12:32:27] [CullThread/INFO] (Minecraft) [STDERR]: java.lang.NullPointerException
```

```
[12:37:40] [CullThread/INFO] (Minecraft) [STDERR]: java.lang.NullPointerException
[12:37:46] [CullThread/INFO] (Minecraft) [STDERR]: java.lang.NullPointerException: Cannot invoke "dev.tr7zw.entityculling.versionless.access.Cullable.isForcedVisible()" because "cullable" is null
[12:37:46] [CullThread/INFO] (Minecraft) [STDERR]: 	at dev.tr7zw.entityculling.CullTask.cullBlockEntities(CullTask.java:155)
[12:37:46] [CullThread/INFO] (Minecraft) [STDERR]: 	at dev.tr7zw.entityculling.CullTask.run(CullTask.java:69)
[12:37:46] [CullThread/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[12:37:47] [CullThread/INFO] (Minecraft) [STDERR]: java.lang.NullPointerException
[12:37:52] [CullThread/INFO] (Minecraft) [STDERR]: java.lang.ArrayIndexOutOfBoundsException: Index 152 out of bounds for length 129
[12:37:52] [CullThread/INFO] (Minecraft) [STDERR]: 	at it.unimi.dsi.fastutil.objects.Object2ObjectLinkedOpenHashMap$MapIterator.nextEntry(Object2ObjectLinkedOpenHashMap.java:1156)
[12:37:52] [CullThread/INFO] (Minecraft) [STDERR]: 	at it.unimi.dsi.fastutil.objects.Object2ObjectLinkedOpenHashMap$EntryIterator.next(Object2ObjectLinkedOpenHashMap.java:1267)
[12:37:52] [CullThread/INFO] (Minecraft) [STDERR]: 	at it.unimi.dsi.fastutil.objects.Object2ObjectLinkedOpenHashMap$EntryIterator.next(Object2ObjectLinkedOpenHashMap.java:1249)
[12:37:52] [CullThread/INFO] (Minecraft) [STDERR]: 	at dev.tr7zw.entityculling.CullTask.cullBlockEntities(CullTask.java:142)
[12:37:52] [CullThread/INFO] (Minecraft) [STDERR]: 	at dev.tr7zw.entityculling.CullTask.run(CullTask.java:69)
[12:37:52] [CullThread/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[12:37:53] [CullThread/INFO] (Minecraft) [STDERR]: java.lang.NullPointerException
```

Why do I report here what looks like a tr7zw problem? Because it happens only when fabric tailor is loaded. 

**To Reproduce**

1. 1.20.6 fabric
2. Install Fabric Tailor 2.4.1
3. Install Entity Culling 1.6.4
4. Error may spit out during gameplay, may take a while

**Logs**

If you have any errors, please paste them as well. If possible, please use pasting site.

*Are you using any other mods?*

Can reproduce with only Entity Culling and Fabric Tailor (and dependencies like fabric api).

**Comment by MeeniMc** [comment]
tr7zw says it is improbable that Fabric Tailor is to blame and the fact that it happens only in conjunction is circumstantial. Closing until proven otherwise then.
