### ISSUE TITLE
[BUG] Incompatibility with TicTACS mod

### ISSUE THREAD

**Issue by FACS01-01** [samolego/FabricTailor#11]
I have a paid account but wanted to play with friends w/o accouts in offline mode.
I tried to set my own skin (player name: FACS01), but didn't work and I got kicked out of the server.
Now when I try to join, I get kicked with message: Internal server error
Console: (I removed my **IP**)
[18:01:08] [Server thread/INFO]: FACS01[/**IP**:52503] logged in with entity id 225 at (-124.3172405731118, 68.0, -16.54763063606454)
[18:01:08] [Server thread/INFO]: FACS01 joined the game
[18:01:09] [Server thread/WARN]: Failed to handle packet for /**IP**:52503
java.lang.NullPointerException: null
	at net.minecraft.class_3222.reloadSkin(class_3222.java:4153) ~[intermediary-server.jar:?]
	at net.minecraft.class_3222.setSkin(class_3222.java:4195) ~[intermediary-server.jar:?]
	at net.minecraft.class_3324.handler$zic001$onPlayerConnect(class_3324.java:1960) ~[intermediary-server.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:273) ~[intermediary-server.jar:?]
	at net.minecraft.class_3248.method_14384(class_3248.java:113) ~[intermediary-server.jar:?]
	at net.minecraft.class_3248.redirect$zhi000$handlePlayerJoin(class_3248.java:562) ~[intermediary-server.jar:?]
	at net.minecraft.class_3248.method_18785(class_3248.java:65) ~[intermediary-server.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:228) ~[intermediary-server.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:173) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:312) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
[18:01:20] [Server thread/INFO]: FACS01 lost connection: Internal server error
[18:01:20] [Server thread/INFO]: FACS01 left the game

mods:
fabric-api-0.28.3+1.16
fabrictailor_fabric-1.4.0-1.16.4
fabriczero-0.1.4
lithium-fabric-mc1.16.4-0.6.0
phosphor-fabric-mc1.16.3-0.7.0+build.10
randompatches-1.16.1-0.0.0.5-fabric
tic-tacs-0.1.2

**Comment by FACS01-01** [comment]
doing a bit more testing, the bug happens when setting other player's skin to myself as well, and logging out. When trying to join back in the bug occurs

**Comment by samolego** [comment]
Hi, thanks for the report.
Sadly I cannot reproduce it :(. I tried setting your skin to myself and to others, then leaving and rejoining ... My guess would be that https://github.com/samolego/FabricTailor/blob/6ddd19764e8d46999e3844dc1a21dfcb8b635168/src/main/java/org/samo_lego/fabrictailor/mixin/ServerPlayerEntityMixin_TailoredPlayer.java#L48 throws it.

Could you try [this build](https://github.com/samolego/FabricTailor/suites/1715522368/artifacts/32403588)?

**Comment by FACS01-01** [comment]
Nope still happening, it even kicks me out faster I think hahah.
But removing the other mods I was using I saw that the bug happens when having [Tic-TACS 0.1.2](https://github.com/Gegy/tic-tacs/releases) installed alongside FabricTailor (and Fabric API). Could there be some incompatibility?
The console's output was the same.

**Comment by samolego** [comment]
Yeah, it might be a compatibility issue. I'll try to reproduce it and see what I can do.

**Comment by Meeni-mc** [comment]
Should rename the issue, I was about to report that same problem again ;)

Still present in TicTacs 0.1.3 so far.

**Comment by samolego** [comment]
Yeah, I've also reported it to Gegy on TicTacs issue tracker.
