### ISSUE TITLE
[BUG] Game Crashes when joining servers OR single-player worlds

### ISSUE THREAD

**Issue by MyNameIsJestus** [samolego/FabricTailor#123]
## Issue

- [ ] Getting crashes everytime you join the world. 

When you join server, theres always 

To Reproduce You need to follow these steps:

1. Join Server;
2. Go to FTailor menu (K by default, but you already know that);
3. Go to capes thingy;
4. Write down "0" in capes URL, then press apply.

AND, It works when you open inventory GUI OR FTailor GUI

Logging yooo

Full Crash-Report.

---- Minecraft Crash Report ----
// There are four lights!

Time: 2024-11-02 17:11:21
Description: Unexpected error

java.lang.IllegalArgumentException: Invalid profile texture url
	at knot//com.mojang.authlib.minecraft.MinecraftProfileTexture.getHash(MinecraftProfileTexture.java:45)
	at knot//customskinloader.fake.FakeMinecraftProfileTexture.getHash(FakeMinecraftProfileTexture.java:48)
	at knot//net.minecraft.class_1071.method_4651(class_1071.java:66)
	at knot//net.minecraft.class_1071.method_22819(class_1071.java:121)
	at knot//com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at knot//net.minecraft.class_1071.method_4655(class_1071.java:119)
	at knot//com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:226)
	at knot//com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:213)
	at knot//net.minecraft.class_1041.method_15998(class_1041.java:288)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1241)
	at knot//net.minecraft.class_310.method_1514(class_310.java:802)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//com.mojang.authlib.minecraft.MinecraftProfileTexture.getHash(MinecraftProfileTexture.java:45)
	at knot//customskinloader.fake.FakeMinecraftProfileTexture.getHash(FakeMinecraftProfileTexture.java:48)
	at knot//net.minecraft.class_1071.method_4651(class_1071.java:66)
	at knot//net.minecraft.class_1071.method_22819(class_1071.java:121)
	at knot//com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at knot//net.minecraft.class_1071.method_4655(class_1071.java:119)
	at knot//com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:226)
	at knot//com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:213)

-- Affected level --
Details:
	All players: 1 total; [class_746['MyNameIsJestus'/71, l='ClientLevel', x=8.73, y=-60.00, z=-6.24]]
	Chunk stats: 1024, 661
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 386 game time, 386 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at knot//net.minecraft.class_638.method_8538(class_638.java:458)
	at knot//net.minecraft.class_310.method_1587(class_310.java:2406)
	at knot//net.minecraft.class_310.method_1514(class_310.java:826)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, Moonlight Mods Dynamic Assets

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 23.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 780803656 bytes (744 MiB) / 3699376128 bytes (3528 MiB) up to 8522825728 bytes (8128 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5700U with Radeon Graphics         
	Identifier: AuthenticAMD Family 23 Model 104 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 1.80
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x164c
	Graphics card #0 versionInfo: DriverVersion=31.0.21912.14
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 31578.56
	Virtual memory used (MB): 14528.20
	Swap memory total (MB): 15872.00
	Swap memory used (MB): 199.16
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx8128m
	Fabric Mods: 
		advancedcompass: Advanced Compass 1.2.15
		amendments: Amendments 1.20-1.2.11
		another_furniture: Another Furniture 1.20.1-3.0.1
		architectury: Architectury 9.1.12
		areas: Areas 5.9
		betterthirdperson: Better Third Person 1.9.0
		blockus: Blockus 2.7.6+1.20.1
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.1
		brewinandchewin: Brewin And Chewin 3.0.6+1.20.1
			mm: Manningham Mills 2.3
		carryon: Carry On 2.1.2.7
		chimes: Chimes 2.0.1
		citresewn: CIT Resewn 1.1.3+1.20
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.20
		clickthrough: ClickThrough 1.20-fabric0.83.0-0.4.1
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
			gbfabrictools: GBfabrictools 1.4+1.20
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.70
		continuity: Continuity 3.0.0-beta.4+1.20.1
		creativecore: CreativeCore 2.11.15
			net_minecraftforge_eventbus: eventbus 6.0.3
		customskinloader: CustomSkinLoader 14.20
		deathlog: DeathLog 0.3.2+1.20
		debugify: Debugify 1.20.1+2.0
		doapi: Lets Do Api 1.2.8
		dramaticdoors: Dramatic Doors (QuiFabrge) 1.20.1-3.2.7
		elytratrims: Elytra Trims 3.4.0
			conditional-mixin: conditional mixin 0.6.2
			mixinsquared: MixinSquared 0.1.2-beta.4
		emotecraft: Emotecraft 2.2.7-a.build.49
			bendy-lib: Bendy api 4.0.0
		ends_delight: End's Delight 2.1
			porting_lib_config: Porting Lib Config 2.3.4+1.20.1
				com_electronwill_night-config_core: core 3.6.6
				com_electronwill_night-config_toml: toml 3.6.6
				porting_lib_core: Porting Lib Core 2.3.4+1.20.1
		entityculling: EntityCulling 1.6.6
		exposure: Exposure 1.7.7
		extraorigins: Extra Origins 1.20-4
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.10.9+kotlin.1.9.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.22.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.0
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		fabrictailor: Fabric Tailor 2.1.2
			config2brigadier: Config to Brigadier 1.2.3
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
		farmersdelight: Farmer's Delight 1.20.1-2.1.6+refabricated
			porting_lib_accessors: Porting Lib Accessors 2.3.4+1.20.1
			porting_lib_base: Porting Lib Base 2.3.4+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.4+1.20.1
				porting_lib_common: Porting Lib Common 2.3.4+1.20.1
				porting_lib_entity: Porting Lib Entity 2.3.4+1.20.1
				porting_lib_extensions: Porting Lib Extensions 2.3.4+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.4+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.4+1.20.1
				porting_lib_transfer: Porting Lib Transfer 2.3.4+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.4+1.20.1
			porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.4+1.20.1
			porting_lib_loot: Porting Lib Loot 2.3.4+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.4+1.20.1
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 2.3.4+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.4+1.20.1
		farmersrespite: Farmer's Respite 3.0.2
		forgeconfigapiport: Forge Config API Port 8.0.0
		glowingbanners: Glow Banners 1.3.2
		icarus: Icarus 1.16
		immersive_paintings: Immersive Paintings 0.6.7+1.20.1
		indium: Indium 1.0.27+mc1.20.1
		inventoryprofilesnext: Inventory Profiles Next 1.10.8
		invisframes: Invisible Frames 2.2.2
			tf_ssf_sfort_ini_sf-ini: SF-INI 1
		invisible_light: Invisible Light 1.0.0
		iris: Iris 1.6.9
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemphysic: ItemPhysic 1.7.0
		java: Java HotSpot(TM) 64-Bit Server VM 23
		jei: Just Enough Items 15.2.0.27
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lambdynlights: LambDynamicLights 2.3.2+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
			spruceui: SpruceUI 5.0.0+1.20
		libipn: libIPN 4.0.1
		litematica: Litematica 0.15.3
		malilib: MaLiLib 0.16.3
		many_flowers: ManyFlowers 1.20.1-1.5
			ducky-updater-lib: Ducky Updater Lib 2023.10.1
		midnightlib: MidnightLib 1.4.1
		minecraft: Minecraft 1.20.1
		minihud: MiniHUD 0.27.0
		moborigins: Mob Origins 1.11.1
		modmenu: Mod Menu 7.2.2
		moonlight: Moonlight 1.20-2.13.0
		more_armor_trims: More Armor Trims 1.4.0-1.20.1
		moremobvariants: More Mob Variants 1.3.1
		nethersdelight: Nether's Delight Refabricated 1.20.1-4.1.1
		noxesium: Noxesium 1.0.3+9b339b0
			com_noxcrew_noxesium_api_: api 1.0.3+9b339b0
		origins: Origins 1.10.0
			apoli: Apoli 2.9.0
				additionalentityattributes: Additional Entity Attributes 1.3.0+1.20.0
				calio: Calio 1.11.0
				cardinal-components-base: Cardinal Components API (base) 5.2.1
				cardinal-components-entity: Cardinal Components API (entities) 5.2.1
				playerabilitylib: Pal 1.8.0
			reach-entity-attributes: Reach Entity Attributes 2.4.0
		oth3r-sit: Sit! 1.1.3+1.20-1.20.1
		owo: oωo 0.11.2+1.20
			blue_endless_jankson: jankson 1.2.2
		pehkui: Pehkui 3.7.11+1.14.4-1.20.2
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		player-animator: Player Animator 1.0.2-rc1+1.20
		plushies: Plushie Mod 1.3.0
		pneumonocore: PneumonoCore 1.0.9+1.20
		presencefootsteps: Presence Footsteps 1.9.0
			kirin: Kirin UI 1.15.0
		shulkerboxtooltip: Shulker Box Tooltip 4.0.4+1.20.1
		sodium: Sodium 0.5.3
		sodium-extra: Sodium Extra 0.5.1+mc1.20.1-build.112
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		supplementaries: Supplementaries 1.20-2.8.17
		trinkets: Trinkets 3.7.2
		umbrellas: Umbrellas 1.0.3+1.20
		vinery: Vinery 1.4.7
		voicechat: Simple Voice Chat 1.20.1-2.5.20
		wi_zoom: WI Zoom 1.5-MC1.20.1
		worldedit: WorldEdit 7.2.15+6463-5ca4dff
		worldeditcui: WorldEditCUI 1.20+01
		xaeroworldmap: Xaero's World Map 1.37.7
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.20.1-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: AMD Radeon(TM) Graphics GL version 3.2.0 Core Profile Context 24.3.1.240216, ATI Technologies Inc.
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: en_us
	CPU: 16x AMD Ryzen 7 5700U with Radeon Graphics 
	Server Running: true
	Player Count: 1 / 8; [class_3222['MyNameIsJestus'/71, l='ServerLevel[New World]', x=8.73, y=-60.00, z=-6.24]]
	Data Packs: vanilla, fabric, Moonlight Mods Dynamic Assets, Supplementaries Generated Pack
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	
Are you using any other mods?

Yes, everything is in report

**Comment by MyNameIsJestus** [comment]
Just found out solution, Just need to use /skin clear, lmao.
