### ISSUE TITLE
[BUG] Infinite loading screen

### ISSUE THREAD

**Issue by MaoDoBan** [samolego/FabricTailor#2]
**Describe the bug**
Infinite loading screen after i run "/setskin player MaoDoBan", and on the server, my friend doing the same command.
After i kicked me from console, i rejoin without the skin.

**Logs**
[00:35:38] [Netty Epoll Server IO #0/INFO]: Player MaoDoBan joined with a matching carpet client
Exception in thread "Thread-79" [00:35:50] [Thread-79/INFO]: [STDERR]: java.lang.IllegalStateException: Removing entity while ticking!
[00:35:50] [Thread-79/INFO]: [STDERR]:  at net.minecraft.class_3218.method_18774(class_3218.java:907)
[00:35:50] [Thread-79/INFO]: [STDERR]:  at net.minecraft.class_3218.redirect$zli000$crashRemovePlayer(class_3218.java:5484)
[00:35:50] [Thread-79/INFO]: [STDERR]:  at net.minecraft.class_3218.method_18770(class_3218.java:923)
[00:35:50] [Thread-79/INFO]: [STDERR]:  at net.minecraft.class_3222.method_14251(class_3222.java:1431)
[00:35:50] [Thread-79/INFO]: [STDERR]:  at org.samo_lego.fabrictailor.FabricTailor.reloadSkin(FabricTailor.java:131)
[00:35:50] [Thread-79/INFO]: [STDERR]:  at org.samo_lego.fabrictailor.FabricTailor.setPlayerSkin(FabricTailor.java:85)
[00:35:50] [Thread-79/INFO]: [STDERR]:  at org.samo_lego.fabrictailor.Command.SetskinCommand.lambda$fetchSkinByName$8(SetskinCommand.java:163)
[00:35:50] [Thread-79/INFO]: [STDERR]:  at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-80" [00:35:54] [Thread-80/INFO]: [STDERR]: java.lang.IllegalStateException: Removing entity while ticking!
[00:35:54] [Thread-80/INFO]: [STDERR]:  at net.minecraft.class_3218.method_18774(class_3218.java:907)
[00:35:54] [Thread-80/INFO]: [STDERR]:  at net.minecraft.class_3218.redirect$zli000$crashRemovePlayer(class_3218.java:5484)
[00:35:54] [Thread-80/INFO]: [STDERR]:  at net.minecraft.class_3218.method_18770(class_3218.java:923)
[00:35:54] [Thread-80/INFO]: [STDERR]:  at net.minecraft.class_3222.method_14251(class_3222.java:1431)
[00:35:54] [Thread-80/INFO]: [STDERR]:  at org.samo_lego.fabrictailor.FabricTailor.reloadSkin(FabricTailor.java:131)
[00:35:54] [Thread-80/INFO]: [STDERR]:  at org.samo_lego.fabrictailor.FabricTailor.setPlayerSkin(FabricTailor.java:85)
[00:35:54] [Thread-80/INFO]: [STDERR]:  at org.samo_lego.fabrictailor.Command.SetskinCommand.lambda$fetchSkinByName$8(SetskinCommand.java:163)
[00:35:54] [Thread-80/INFO]: [STDERR]:  at java.lang.Thread.run(Thread.java:748)
[00:48:19] [Server thread/INFO]: Must_Titan lost connection: Disconnected
[00:48:19] [Server thread/INFO]: Must_Titan left the game
kick MaoDoBan
[00:48:37] [Server thread/INFO]: MaoDoBan lost connection: Disconnected
[00:48:37] [Server thread/INFO]: MaoDoBan left the game
[00:48:37] [Server thread/INFO]: Kicked MaoDoBan: Kicked by an operator
[00:48:37] [Server thread/WARN]: handleDisconnection() called twice

**Are you using any other mods?**
carpet-extra-1.16-1.4.0
fabric-carpet-1.16-1.4.0+v200623
lithium-fabric-mc1.16.1-0.5.0
phosphor-fabric-mc1.16.1-0.6.0+build.7
terrestria-2.0.3+build.46
traverse-2.2.12+build.24

**Additional context**
This server runs on a host.
I run the same command alone on server and it works.

**Comment by samolego** [comment]
Can you try release 1.1.0? It hopefully fixes this issue.
