### ISSUE TITLE
[?] Malformed URL

### ISSUE THREAD

**Issue by kvvu** [samolego/FabricTailor#26]
**Describe the bug**
when using /skin set url , the error message shows up
![unknown-2](https://user-images.githubusercontent.com/73371799/115114082-ac17bb00-9fb7-11eb-9d52-25c0ec263d7d.png)

**To Reproduce**
1. /skin set url (imgur link .png)

**Logs**
If you have any errors, please paste them as well. If possible, please use pasting site.

**Are you using any other mods?
Origins , Mob Origins , Extra Origins, Pehkui

**Additional context**

**Comment by kvvu** [comment]
`[13:20:49] [pool-2-thread-3/INFO]: [STDERR]: java.net.ConnectException: Connection refused (Connection refused)
[13:20:49] [pool-2-thread-3/INFO]: [STDERR]: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
[13:20:49] [pool-2-thread-3/INFO]: [STDERR]: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[13:20:49] [pool-2-thread-3/INFO]: [STDERR]: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[13:20:49] [pool-2-thread-3/INFO]: [STDERR]: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[13:20:49] [pool-2-thread-3/INFO]: [STDERR]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[13:20:49] [pool-2-thread-3/INFO]: [STDERR]: 	at java.net.Socket.connect(Socket.java:589)
[13:20:49] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
[13:20:49] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[13:20:49] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[13:20:49] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[13:20:49] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[13:20:49] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[13:20:49] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[13:20:49] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[13:20:49] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
[13:20:49] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
[13:20:49] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[13:20:49] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
[13:20:49] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
[13:20:49] [pool-2-thread-3/INFO]: [STDERR]: 	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
[13:20:49] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
[13:20:49] [pool-2-thread-3/INFO]: [STDERR]: 	at org.samo_lego.fabrictailor.command.SkinCommand.urlRequest(SkinCommand.java:342)
[13:20:49] [pool-2-thread-3/INFO]: [STDERR]: 	at org.samo_lego.fabrictailor.command.SkinCommand.lambda$fetchSkinByUrl$11(SkinCommand.java:205)
[13:20:49] [pool-2-thread-3/INFO]: [STDERR]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[13:20:49] [pool-2-thread-3/INFO]: [STDERR]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:20:49] [pool-2-thread-3/INFO]: [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:20:49] [pool-2-thread-3/INFO]: [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:20:49] [pool-2-thread-3/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:748`


LOG

**Comment by samolego** [comment]
Could you append the skin link as well? This might sound silly, but are you sure you have valid connection?

**Comment by kvvu** [comment]
yes, we all have a valid internet connection.
here's the link : https://i.imgur.com/qiHXuRQ.png

**Comment by samolego** [comment]
Humm, try running it through mineskin.org. if it errors, this is connected to #25 :(

**Comment by kvvu** [comment]
Malformed URL.
