### ISSUE TITLE
[BUG] Server crashing with Taterzens 1.2.0

### ISSUE THREAD

**Issue by Londiuh** [samolego/FabricTailor#36]
**Describe the bug**
Server crashes when fetching a skin for a player if you have Taterzens.

**To Reproduce**
1. Launch the server with FabricTailor & Taterzens
2. Use `/skin set player playerName`

**Logs**
```log
[20:24:18] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: org/samo_lego/taterzens/interfaces/TaterzenEditor
	at org.samo_lego.fabrictailor.compatibility.TaterzensCompatibility.setTaterzenSkin(TaterzensCompatibility.java:11) ~[fabrictailor-1.6.1.jar:?]
	at org.samo_lego.fabrictailor.util.SkinFetcher.lambda$fetchSkinByName$0(SkinFetcher.java:135) ~[fabrictailor-1.6.1.jar:?]
	at net.minecraft.class_2631.method_37430(class_2631.java:151) ~[intermediary-server.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MixinMinecraftServer.java:788) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MixinMinecraftServer.java:164) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MixinMinecraftServer.java:770) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MixinMinecraftServer.java:764) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MixinMinecraftServer.java:749) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MixinMinecraftServer.java:701) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MixinMinecraftServer.java:270) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: org.samo_lego.taterzens.interfaces.TaterzenEditor
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:57) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	... 16 more
[20:24:18] [Server thread/ERROR]: This crash report has been saved to: /home/dennis/Documents/pija3/./crash-reports/crash-2021-08-06_20.24.18-server.txt
[20:24:18] [Server thread/INFO]: Waiting for 1 bucket(s) to finish. Average queue size of 0 requests
[20:24:19] [Server thread/INFO]: Stopping server
[20:24:19] [Server thread/INFO]: Saving players
[20:24:19] [Server thread/INFO]: TheLondiux lost connection: Internal Exception: java.lang.StackOverflowError
```

**Are you using any other mods?**
- Taterzens 1.2.0
- fabric api 0.37.1

**Additional context**
1.17.1

**Comment by Londiuh** [comment]
also crashing with taterzens 1.3.0

**Comment by Londiuh** [comment]
On June 18th the `TaterzenEditor` interface was renamed to `ITaterzenEditor`

**Comment by James103** [comment]
Fabric Tailor version 1.6.2 has not been released yet. To workaround this bug, do the following (tested on Windows):
1. Clone the latest version of this mod's repository to a new directory.
2. Inside the new directory, run `gradlew build` in a command line terminal.
3. Wait until the build completes.
4. Add the newly generated `...\FabricTailor-master\build\libs\fabrictailor-1.6.1.jar` file to your Minecraft instance's mods folder, replacing any existing jar of the same name.
5. Restart Minecraft.
