### ISSUE TITLE
[BUG] Crash upon trying to launch without internet connection

### ISSUE THREAD

**Issue by alexmozaidze** [samolego/FabricTailor#43]
**Describe the bug**

The game crashes when I try to launch the game without internet connection. I join the world, and upon loading it kicks me out saying it doesn't like my player data. In console, I saw that it tried to fetch Mojang servers before kicking me out. And that's not the worst part, the worst part is that when I close the game, java process is still up and it hogs more and more memory, TLauncher console's button to forcefully close minecraft suddenly doesn't work and all I'm left to do is kill the java process with `killall -SIGKILL java`.
When I connect to internet, it works with no errors.

**To Reproduce**

1. Turn off internet
2. Launch Minecraft with the mod enabled
3. **Suffering**

**Logs**

I forgot the name of the log. I will provide it

*Are you using any other mods?*

Yeah, and a lot of them, but I don't think any of them would somehow interfere with FabricTailor. I will provide mod list with logs

**Additional context**

My internet provider hates me

**Comment by samolego** [comment]
Tlauncher is not supported, although this is probably the case with official one as well.

**Comment by NikitaCartes** [comment]
Similar issue as I can tell
```
-- Head --
Thread: Server Watchdog
Stacktrace:
	at java.base@17.0.1/sun.nio.ch.Net.connect0(Native Method)
	at java.base@17.0.1/sun.nio.ch.Net.connect(Net.java:579)
	at java.base@17.0.1/sun.nio.ch.Net.connect(Net.java:568)
	at java.base@17.0.1/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base@17.0.1/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base@17.0.1/java.net.Socket.connect(Socket.java:633)
	at java.base@17.0.1/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299)
	at java.base@17.0.1/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
	at java.base@17.0.1/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
	at java.base@17.0.1/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
	at java.base@17.0.1/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
	at java.base@17.0.1/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base@17.0.1/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
	at java.base@17.0.1/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
	at java.base@17.0.1/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
	at java.base@17.0.1/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at java.base@17.0.1/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
	at java.base@17.0.1/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
	at java.base@17.0.1/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base@17.0.1/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at java.base@17.0.1/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
	at org.samo_lego.fabrictailor.util.SkinFetcher.urlRequest(SkinFetcher.java:162)
	at org.samo_lego.fabrictailor.util.SkinFetcher.fetchSkinByName(SkinFetcher.java:75)
	at net.minecraft.class_3324.handler$bbl003$onPlayerConnect(class_3324.java:4964)
	at net.minecraft.class_3324.method_14570(class_3324.java:145)
	at net.minecraft.class_3248.method_33800(class_3248.java:130)
	at net.minecraft.class_3248.method_14384(class_3248.java:117)
	at net.minecraft.class_3248.redirect$zpj000$handlePlayerJoin(class_3248.java:1063)
	at net.minecraft.class_3248.method_18785(class_3248.java:67)
	at net.minecraft.class_2535.method_10754(class_2535.java:234)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:890)
	at net.minecraft.class_3176.method_3813(class_3176.java:324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.handler$zbk000$modifiedRunLoop(MinecraftServer.java:3356)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:663)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
```
