### ISSUE TITLE
Crash on server startup

### ISSUE THREAD

**Issue by NicolasPL64** [samolego/FabricTailor#61]
I'm getting this error when starting the server, and I have downloaded the 1.19 version of both the server and the mod.

[12:05:34] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.8
[12:05:34] [main/WARN]: Mod resolution failed
[12:05:34] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE fabrictailor 1.8.4 {depends fabric @ [*]}, ROOT_FORCELOAD_SINGLE fabrictailor 1.8.4]
[12:05:34] [main/INFO]: Reason: [HARD_DEP fabrictailor 1.8.4 {depends fabric @ [*]}, HARD_DEP config2brigadier 1.1.3 {depends fabric @ [*]}]
[12:05:34] [main/INFO]: Fix: add [add:fabric 1 ([(-?,?)])], remove [], replace []
[12:05:34] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, any version.
Unmet dependency listing:
	 - Mod 'Fabric Tailor' (fabrictailor) 1.8.4 requires any version of fabric, which is missing!
	 - Mod 'Config to Brigadier' (config2brigadier) 1.1.3 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19-loader.0.14.8-launcher.0.11.0.jar:0.11.0]

**Comment by NicolasPL64** [comment]
Didn't know I had to download https://www.curseforge.com/minecraft/mc-mods/fabric-api

Fixed
