### ISSUE TITLE
[BUG] Game crashes trying to open the mod menu

### ISSUE THREAD

**Issue by JuanFricke** [samolego/FabricTailor#85]
**Describe the bug**

I'm using the 1.20.2 update, server-side works perfectly with the commands(running my server on a Debian based system) but on local worlds or server, the game crashes when opening the mod menu (via key bind or button on skin config)
Only the player crashes, the server continues running:

I'm thinking that could be some incompatibility with some other mod i'm using, but i'm not shure

**Logs + mods list**

```

---- Minecraft Crash Report ----
// You're mean.

Time: 2023-09-26 00:07:49
Description: Rendering screen

java.lang.IllegalAccessError: class org.samo_lego.fabrictailor.client.screen.SkinChangeScreen tried to access private field net.minecraft.class_457.field_2717 (org.samo_lego.fabrictailor.client.screen.SkinChangeScreen and net.minecraft.class_457 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @57175e74)
	at org.samo_lego.fabrictailor.client.screen.SkinChangeScreen.method_25394(SkinChangeScreen.java:224)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:946)
	at net.minecraft.class_310.method_1523(class_310.java:1275)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.samo_lego.fabrictailor.client.screen.SkinChangeScreen.method_25394(SkinChangeScreen.java:224)
	at net.minecraft.class_437.method_47413(class_437.java:110)

-- Screen render details --
Details:
	Screen name: org.samo_lego.fabrictailor.client.screen.SkinChangeScreen
	Mouse location: Scaled: (640, 252). Absolute: (1280.000000, 504.000000)
	Screen size: Scaled: (1280, 505). Absolute: (2560, 1009). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:946)
	at net.minecraft.class_310.method_1523(class_310.java:1275)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['juanfricke'/2838, l='ClientLevel', x=166.00, y=66.94, z=278.52]]
	Chunk stats: 1024, 453
	Level dimension: minecraft:overworld
	Level spawn location: World: (136,64,256), Section: (at 8,0,0 in 8,4,16; chunk contains blocks 128,-64,256 to 143,319,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 13585275 game time, 15562806 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:451)
	at net.minecraft.class_310.method_1587(class_310.java:2481)
	at net.minecraft.class_310.method_1514(class_310.java:875)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: vanilla, file/VanillaTweaks_r457571.zip, fabric, server

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 368003896 bytes (350 MiB) / 1275068416 bytes (1216 MiB) up to 13723762688 bytes (13088 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz
	Identifier: Intel64 Family 6 Model 63 Stepping 2
	Microarchitecture: Haswell (Server)
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 20
	Graphics card #0 name: AMD Radeon RX 5700 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x731f
	Graphics card #0 versionInfo: DriverVersion=31.0.21001.45002
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.67
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.40
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 34654.12
	Virtual memory used (MB): 23584.27
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 5.80
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx13080M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.10.126
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.10.126
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.10.126
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.10.126
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.10.126
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.10.126
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.10.126
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.10.126
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.10.126
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.10.126
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.10.126
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.10.126
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.10.126
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.10.126
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.10.126
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.10.126
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.10.126
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.10.126
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.126
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.10.126
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.126
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		camerautils: Camera Utils 1.20.2-1.0.5
			fabric-api-base: Fabric API Base 0.4.32+fce67b3203
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+f4b7e42403
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.25+3bafade303
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+86b1264503
		clean-debug: Clean F3 0.4.1
		clickopener: Click Opener Mod 3.0.0-alpha+1.20.1
		cloth-config: Cloth Config v12 12.0.109
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 13.0.0.1
		collective: Collective 6.66
		doubledoors: Double Doors 5.0
		drops-into-shulker: Drops into Shulker 1.2.2
		dynamic_fps: Dynamic FPS 3.2.0
		eatinganimationid: Eating Animation 1.9.4+1.20
		entity_model_features: Entity Model Features 1.0.2
		entity_texture_features: Entity Texture Features 4.5.1
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20.1
		fabric-api: Fabric API 0.89.2+1.20.2
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.40+fce67b32a0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.11+86b12645a0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+73761d2ea0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+73761d2ea0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.42+f4b7e424a0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.3+86b12645a0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.35+f71b366fa0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.14+86b12645a0
			fabric-commands-v0: Fabric Commands (v0) 0.2.52+df3654b3a0
			fabric-containers-v0: Fabric Containers (v0) 0.1.71+df3654b3a0
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.3+0ba8e9cea0
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.6+f4b7e424a0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+f4b7e424a0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.1+bbae80faa0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.55+b1229956a0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.24+f4b7e424a0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.8+daef22a2a0
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.67+df3654b3a0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+f4b7e424a0
			fabric-item-api-v1: Fabric Item API (v1) 2.1.31+43511215a0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+f4b7e424a0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b3a0
			fabric-loot-api-v2: Fabric Loot API (v2) 2.0.1+0ba8e9cea0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.0+fce67b32a0
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.53+f4b7e424a0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.4+f4b7e424a0
			fabric-models-v0: Fabric Models (v0) 0.4.3+9386d8a7a0
			fabric-networking-api-v1: Fabric Networking API (v1) 3.0.7+74a33ae7a0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 12.1.0+b1b4f7b0a0
			fabric-particles-v1: Fabric Particles (v1) 1.1.3+f4b7e424a0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.4+43511215a0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.2+34a3e0e2a0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+2034447ca0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+2034447ca0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.47+df3654b3a0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.38+73761d2ea0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.29+f4b7e424a0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.50+df3654b3a0
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.9+86b12645a0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+43511215a0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.10+0ba8e9cea0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.37+86b12645a0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+f4b7e424a0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.7+109a65e5a0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.2+fce67b32a0
		fabric-language-kotlin: Fabric Language Kotlin 1.10.10+kotlin.1.9.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.22.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.0
		fabricloader: Fabric Loader 0.14.22
		fabricskyboxes: FabricSkyBoxes 0.7.3+mc1.20.2
		fabrictailor: Fabric Tailor 2.2.0
			config2brigadier: Config to Brigadier 1.2.3
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
		fallingleaves: Falling Leaves 1.15.3
		fallingtree: FallingTree 5.0.0
		ferritecore: FerriteCore 6.0.0
		fishontheline: Fish On The Line 3.0
		guiclock: GUI Clock 4.2
		guicompass: GUI Compass 4.2
		handoveryouritems: Hand Over Your Items 3.0
		indium: Indium 1.0.27+mc1.20.1
		inventoryprofilesnext: Inventory Profiles Next 1.10.7
		iris: Iris 1.6.9
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		jade: Jade 12.1.3
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.14
			journeymap-api-fabric: JourneyMap API 1.20.2-1.9-fabric-SNAPSHOT
		lambdynlights: LambDynamicLights 2.3.2+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
			spruceui: SpruceUI 5.0.0+1.20
		lazydfu: LazyDFU 0.1.3
		libipn: libIPN 4.0.0
		lithium: Lithium 0.12.0
		make_bubbles_pop: Make Bubbles Pop Mod 0.2.0-fabric
		midnightlib: MidnightLib 1.5.0
		minecraft: Minecraft 1.20.2
		modmenu: Mod Menu 8.0.0-beta.2
		notenoughanimations: NotEnoughAnimations 1.6.4
		notenoughcrashes: Not Enough Crashes 4.4.6+1.20.2
		ping-wheel: Ping Wheel 1.5.1
		reeses-sodium-options: Reese's Sodium Options 1.6.5+mc1.20.2-build.96
		replantingcrops: Replanting Crops 5.1
		servercore: ServerCore 1.3.8+1.20.2
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-rc.4
			placeholder-api: Placeholder API 2.2.0+1.20.2
		shulkerboxtooltip: Shulker Box Tooltip 4.0.5+1.20.2
		skinlayers: 3d Skin Layers 1.5.5-mc1.20.2
		sodium: Sodium 0.5.3
		sodium-extra: Sodium Extra 0.5.2+mc1.20.2-build.113
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		spark: spark 1.10.54
		starlight: Starlight 1.1.2+fabric.bdaeb21
		visuality: Visuality 0.7.1+1.20
		waveycapes: WaveyCapes 1.3.2
		whereisit: WhereIsIt 2.1.1+1.20.2
			jackfredlib: JackFredLib 0.5.6+1.20.2
				jackfredlib-base: JackFredLib: Base 1.1.1+1.20.2
				jackfredlib-colour: JackFredLib: Colour 1.0.1+1.20.2
				jackfredlib-extracommandsourcedata: JackFredLib: Extra Command Source Data 1.0.3+1.20.2
				jackfredlib-lying: JackFredLib: Lying 0.3.1+1.20.2
				jackfredlib-toasts: JackFredLib: Toasts 1.0.2+1.20.2
		yet_another_config_lib_v3: YetAnotherConfigLib 3.1.1+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
	Loaded Shaderpack: Sildur's+Enhanced+Default+v1.16+Fancy.zip
		Profile: Fancy (+0 options changed by user)
	NEC status: No NEC detected
	JVM uptime in seconds: 92.565
	Launched Version: fabric-loader-0.14.22-1.20.2
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: AMD Radeon RX 5700 XT GL version 3.2.0 Core Profile Context 23.7.1.230626, ATI Technologies Inc.
	Window size: 2560x1009
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/VanillaTweaks_r457571.zip (incompatible), fabric
	Current Language: pt_br
	Locale: pt_BR
	CPU: 20x Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Fabric Tailor (fabrictailor)
```

**Comment by samolego** [comment]
Hi, this is already known issue. 1.20.2 version was only built for servers. Also mentioned in releases, but thanks anyway.

**Comment by JuanFricke** [comment]
Oh, sorry, I probably didn't see that on the modrinth page, also, thanks for the mod, has been really fun to use in my local server :)
