### ISSUE TITLE
[BUG] Incompatible with fabric-api >= 0.28

### ISSUE THREAD

**Issue by Meeni-mc** [samolego/FabricTailor#9]
**Describe the bug**
The game crashes during startup with multiple instances of `Invocation Target Exception`.

**To Reproduce**

1. Install minecraft 1.16.4-fabric
2. Install fabric-api-0.28.0 (or 28.1, as currently latest)
3. Install fabric-tailor-1.3.2-1.16.4
4. Launch game, will crash during startup (before menu screen)

**Logs**

```
[19:22:04] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
[19:22:04] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabrictailor.mixins.json:EntityTrackerAccessor and should be specified in value
[19:22:04] [main/WARN]: Error loading class: net/fabricmc/fabric/impl/networking/server/EntityTrackerStreamAccessor (java.lang.ClassNotFoundException: net/fabricmc/fabric/impl/networking/server/EntityTrackerStreamAccessor)
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at minitweaks.MiniTweaks.<clinit>(MiniTweaks.java:11)
	at net.minecraft.client.main.Main.handler$bdf001$loadMe(Main.java:519)
	at net.minecraft.client.main.Main.main(Main.java)
	... 15 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for fabrictailor.mixins.json:MixinServerPlayerEntity during activity: [Transform -> Method reloadSkin()V -> INVOKEINTERFACE -> net/fabricmc/fabric/impl/networking/server/EntityTrackerStreamAccessor::fabric_getTrackingPlayers()Ljava/util/stream/Stream;]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:300)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1272)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 24 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.fabricmc.fabric.impl.networking.server.EntityTrackerStreamAccessor
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:768)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:754)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:720)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:294)
	... 30 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.impl.networking.server.EntityTrackerStreamAccessor
	... 34 more
Exiting with -1
Process exited with code -1.
```

**Comment by samolego** [comment]
This was actually fixed (#8 ). I just haven't uploaded the latest version 😄 .
